version: '3'
services:
  node:
    image: "node:9"
    user: "node"
    working_dir: /src
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/src
    expose:
      - "3000"
    ports: 
      - "3000:3000"
    command: "npm start"
    